services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis_dashboard
    ports:
      - "5540:5540"
    volumes:
      - insight_data:/data
    depends_on:
      - redis
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - "5672:5672"    # AMQP protocol
      - "15672:15672"  # management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - app-network


volumes:
  postgres_data:
  redis_data:
  insight_data:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge